// import AppProvider from "@/store/provider";

import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import AppProvider from "~/store/provider";

// import dynamic from "next/dynamic";
// const AppProvider = dynamic(() => import("@/store/provider"));
const inter = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Husir Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} relative bg-light text-foreground dark:bg-dark dark:text-foreground-dark`}
        id="body"
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
